sudo: required

services:
  - docker

before_install:
  - docker build -t mayurbakale/multidockerreactfibo -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mayurbakale/multidockerreactfibo npm test

after_success:
  - docker build -t mayurbakale/fibo-multi-client ./client
  - docker build -t mayurbakale/fibo-multi-worker ./worker
  - docker build -t mayurbakale/fibo-multi-server ./server
  - docker build -t mayurbakale/fibo-multi-nginx ./nginx
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push mayurbakale/fibo-multi-client
  - docker push mayurbakale/fibo-multi-worker
  - docker push mayurbakale/fibo-multi-server
  - docker push mayurbakale/fibo-multi-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: MultiDocker-env
  env: MultidockerEnv-env
  bucket_name: elasticbeanstalk-us-east-2-205502942541
  bucket_path: fibo-multi-docker
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
